# Generated by Django 3.2 on 2021-04-12 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('B', 'Billing'), ('S', 'Shipping')], default='B', max_length=240)),
                ('street', models.CharField(default='33 Main St', max_length=120)),
                ('city', models.CharField(max_length=240)),
                ('state', models.CharField(max_length=240)),
                ('country', models.CharField(default='Earth', max_length=240)),
                ('postal_code', models.CharField(max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('billing_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.billingprofile')),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
    ]
