# Generated by Django 3.2.3 on 2021-05-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('B', 'Billing'), ('S', 'Shipping')], default='B', max_length=9),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(default='33 Main St', max_length=240),
        ),
    ]
