# Generated by Django 3.2.3 on 2021-05-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_auto_20210516_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(default='', max_length=240),
        ),
    ]
