# Generated by Django 3.2.8 on 2021-10-06 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0004_alter_address_street'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='updated_at',
            new_name='updated',
        ),
    ]
