# Generated by Django 3.2.8 on 2021-10-06 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingprofile',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='created_at',
            new_name='created',
        ),
    ]
