# Generated by Django 4.1 on 2022-08-17 10:01

from django.db import migrations, models
import shorturl.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClUrl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        max_length=240, validators=[shorturl.validators.validate_url]
                    ),
                ),
                ("shortcode", models.CharField(blank=True, max_length=7, unique=True)),
                ("active", models.BooleanField(default=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Clvm short URL",
                "verbose_name_plural": "Clvm short URLs",
                "ordering": ["-updated"],
            },
        ),
    ]
