# Generated by Django 3.2 on 2021-04-12 11:57

from django.db import migrations, models
import shorturl.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=240, validators=[shorturl.validators.validate_url])),
                ('shortcode', models.CharField(blank=True, max_length=7, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Clavem short URL',
                'verbose_name_plural': 'Clavem short URLs',
                'ordering': ['-updated'],
            },
        ),
    ]
