# Generated by Django 3.2.3 on 2021-05-19 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shorturl', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clurl',
            options={'ordering': ['-updated'], 'verbose_name': 'Clvm short URL', 'verbose_name_plural': 'Clvm short URLs'},
        ),
    ]
