# Generated by Django 3.2.8 on 2021-10-06 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objectviewed',
            options={'ordering': ['-created'], 'verbose_name': 'Object Viewed', 'verbose_name_plural': 'Objects Viewed'},
        ),
        migrations.RenameField(
            model_name='objectviewed',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='usersession',
            old_name='created_at',
            new_name='created',
        ),
    ]
