# Generated by Django 3.2.6 on 2021-08-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='item_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19),
        ),
    ]
