# Generated by Django 3.2.6 on 2021-08-26 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_cart_item_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='order_qty',
        ),
    ]
