# Generated by Django 3.2.6 on 2021-08-26 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_remove_cart_order_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='item_total',
        ),
    ]
