# Generated by Django 3.2 on 2021-04-26 15:32

from django.db import migrations, models
import team.models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_alter_member_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='member',
            name='img',
            field=models.FileField(blank=True, help_text='Consistent style', null=True, upload_to=team.models.member_image_path, verbose_name='Picture'),
        ),
    ]
