# Generated by Django 3.2.8 on 2021-10-06 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20210426_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='created_at',
            new_name='created',
        ),
    ]
