# Generated by Django 3.2.5 on 2021-07-07 22:04

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
        migrations.AlterModelOptions(
            name='marketingpreference',
            options={'verbose_name_plural': 'Email Marketing Preference'},
        ),
        migrations.AlterField(
            model_name='marketingpreference',
            name='mailchimp_msg',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marketingpreference',
            name='mailchimp_subscribed',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
