# Generated by Django 3.2.8 on 2021-10-06 14:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_auto_20210707_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketingpreference',
            old_name='updated_at',
            new_name='updated',
        ),
        migrations.RemoveField(
            model_name='marketingpreference',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='marketingpreference',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 10, 6, 14, 3, 54, 383308, tzinfo=utc), verbose_name='Created at'),
            preserve_default=False,
        ),
    ]
