# Generated by Django 4.1 on 2022-08-17 10:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("C", "Collaboration"),
                            ("J", "Job"),
                            ("F", "Feedback"),
                            ("S", "Support"),
                        ],
                        default="C",
                        max_length=255,
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=60, null=True)),
                ("last_name", models.CharField(blank=True, max_length=60, null=True)),
                (
                    "email",
                    models.EmailField(
                        max_length=60,
                        unique=True,
                        validators=[
                            django.core.validators.EmailValidator(
                                allowlist=[
                                    "protonmail",
                                    "tutanota",
                                    "gmail",
                                    "yahoo",
                                    "hotmail",
                                ]
                            )
                        ],
                    ),
                ),
                ("topic", models.CharField(max_length=99)),
                ("text", models.TextField(blank=True, null=True)),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
            ],
            options={
                "verbose_name_plural": "Contacts",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255)),
                ("room", models.CharField(max_length=255)),
                ("text", models.TextField(blank=True, null=True)),
                ("sent", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["sent"],
            },
        ),
    ]
