# Generated by Django 3.2.4 on 2021-06-24 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('sent',)},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='date_added',
            new_name='sent',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='content',
            new_name='text',
        ),
    ]
