# Generated by Django 3.2.4 on 2021-06-25 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20210624_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='postal_code',
        ),
    ]
