# Generated by Django 3.2.4 on 2021-06-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_rename_subject_contact_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['sent']},
        ),
        migrations.AlterField(
            model_name='contact',
            name='message_type',
            field=models.CharField(choices=[('C', 'Collaboration'), ('J', 'Job'), ('F', 'Feedback'), ('S', 'Support')], default='C', max_length=255),
        ),
        migrations.AlterField(
            model_name='contact',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
