# Generated by Django 3.2.5 on 2021-07-02 14:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20210625_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=60, unique=True, validators=[django.core.validators.EmailValidator(whitelist=['protonmail', 'tutanota', 'gmail', 'yahoo', 'hotmail'])]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='topic',
            field=models.CharField(max_length=99),
        ),
    ]
