# Generated by Django 4.1.2 on 2022-10-05 19:29

import disposable_email_checker.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cuser",
            name="email",
            field=disposable_email_checker.fields.DisposableEmailField(
                max_length=254, unique=True
            ),
        ),
    ]
