# Generated by Django 3.2.4 on 2021-06-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_cuser_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuser',
            name='currency',
            field=models.CharField(choices=[('€', 'EUR'), ('$', 'USD')], default='€', max_length=3),
        ),
    ]
