# Generated by Django 3.2.5 on 2021-07-07 22:04

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_cuser_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuser',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.user_image_path, verbose_name='Profile image'),
        ),
    ]
