# Generated by Django 3.2.5 on 2021-07-07 22:25

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_cuser_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuser',
            name='bio',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Bio'),
        ),
    ]
