# Generated by Django 3.2.5 on 2021-07-10 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_cuser_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuser',
            name='currency',
            field=models.CharField(choices=[('€', 'EUR'), ('$', 'USD')], default='$', max_length=3),
        ),
    ]
