# Generated by Django 3.2.5 on 2021-07-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_cuser_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuser',
            name='email',
            field=models.EmailField(max_length=99, unique=True),
        ),
        migrations.AlterField(
            model_name='cuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
        migrations.AlterField(
            model_name='cuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
    ]
