# Generated by Django 3.2.8 on 2021-10-06 14:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210723_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailactivation',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='emailactivation',
            name='update',
        ),
        migrations.AddField(
            model_name='emailactivation',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 10, 6, 14, 3, 46, 183379, tzinfo=utc), verbose_name='Created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailactivation',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
    ]
