# Generated by Django 3.2.4 on 2021-06-17 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0010_auto_20210611_1650'),
        ('notes', '0002_alter_note_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='active',
            field=models.BooleanField(default=True, help_text='Hide insulting ones', verbose_name='Show'),
        ),
        migrations.AlterField(
            model_name='note',
            name='essay',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='essays.essay'),
        ),
    ]
