# Generated by Django 3.2.4 on 2021-06-21 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20210617_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='private',
            field=models.BooleanField(blank=True, default=False, help_text='Hide name/email', null=True),
        ),
    ]
