# Generated by Django 3.2.4 on 2021-06-25 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_note_private'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='private',
        ),
    ]
