# Generated by Django 3.1.7 on 2021-03-30 11:41

import django.core.validators
from django.db import migrations, models
import education.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(default=1, null=True, unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('title', models.CharField(db_index=True, max_length=90)),
                ('slug', models.SlugField(unique=True)),
                ('text', tinymce.models.HTMLField(null=True, verbose_name='Key points')),
                ('audio', models.FileField(blank=True, null=True, upload_to=education.models.book_media_path, verbose_name='Record reading')),
                ('img', models.ImageField(null=True, upload_to=education.models.book_media_path, verbose_name='Cover')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True, verbose_name='Publish')),
                ('tags', models.ManyToManyField(to='tags.Tag')),
            ],
            options={
                'verbose_name_plural': 'Books',
                'ordering': ['index'],
            },
        ),
    ]
