# Generated by Django 4.1 on 2022-08-17 10:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import education.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "index",
                    models.PositiveSmallIntegerField(
                        default=1,
                        null=True,
                        unique=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=90)),
                ("slug", models.SlugField(unique=True)),
                ("summary", tinymce.models.HTMLField(blank=True, null=True)),
                (
                    "audio",
                    models.FileField(
                        blank=True,
                        help_text="Record reading",
                        null=True,
                        upload_to=education.models.book_media_path,
                    ),
                ),
                (
                    "img",
                    models.ImageField(
                        null=True,
                        upload_to=education.models.book_media_path,
                        verbose_name="Cover image",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "active",
                    models.BooleanField(
                        default=False, help_text="Ensure to edit before publishing"
                    ),
                ),
                ("tags", models.ManyToManyField(to="tags.tag")),
            ],
            options={
                "verbose_name_plural": "Books",
                "ordering": ["index"],
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Skip if section 1",
                        max_length=90,
                        null=True,
                    ),
                ),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
                (
                    "text",
                    tinymce.models.HTMLField(
                        help_text='View->srcode->class="fl"', null=True
                    ),
                ),
                (
                    "img",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=education.models.book_media_path,
                        verbose_name="Image",
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="education.book",
                    ),
                ),
            ],
        ),
    ]
