# Generated by Django 3.2 on 2021-04-26 15:32

from django.db import migrations, models
import education.models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_alter_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='active',
            field=models.BooleanField(default=False, help_text='Ensure to edit before publishing'),
        ),
        migrations.AlterField(
            model_name='book',
            name='audio',
            field=models.FileField(blank=True, help_text='Record reading', null=True, upload_to=education.models.book_media_path),
        ),
        migrations.AlterField(
            model_name='book',
            name='text',
            field=tinymce.models.HTMLField(help_text='Key points', null=True),
        ),
    ]
