# Generated by Django 3.2.4 on 2021-06-09 22:35

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_auto_20210426_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='text',
            field=tinymce.models.HTMLField(help_text='View->srcode->class="fl"', null=True),
        ),
    ]
