# Generated by Django 3.2.4 on 2021-06-10 19:58

from django.db import migrations, models
import django.db.models.deletion
import education.models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_alter_book_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Skip if section 1', max_length=90, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('text', tinymce.models.HTMLField(help_text='Exordium (Pathos)-> Narratio -> Confirmatio (Logos) -> Refutatio (Ethos) -> Peroration (Pathos)[View->srcode->class="fl"]', null=True)),
                ('img', models.FileField(blank=True, null=True, upload_to=education.models.book_media_path, verbose_name='Image')),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='education.book')),
            ],
        ),
    ]
