# Generated by Django 3.2.4 on 2021-06-11 16:50

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='text',
        ),
        migrations.AddField(
            model_name='book',
            name='summary',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='text',
            field=tinymce.models.HTMLField(help_text='View->srcode->class="fl"', null=True),
        ),
    ]
