# Generated by Django 3.2.4 on 2021-06-17 13:01

from django.db import migrations, models
import education.models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0008_auto_20210611_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='img',
            field=models.ImageField(null=True, upload_to=education.models.book_media_path, verbose_name='Cover image'),
        ),
    ]
