# Generated by Django 4.1 on 2022-08-17 10:00

from django.db import migrations, models
import django.db.models.deletion
import home.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("C", "Collaboration"),
                            ("J", "Employment"),
                            ("F", "Feedback"),
                            ("M", "Misc"),
                        ],
                        default="C",
                        max_length=255,
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=255, null=True)),
                ("last_name", models.CharField(blank=True, max_length=255, null=True)),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("subject", models.CharField(max_length=255)),
                ("text", tinymce.models.HTMLField(blank=True, null=True)),
                ("postal_code", models.CharField(blank=True, max_length=19, null=True)),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
            ],
            options={
                "verbose_name_plural": "Contacts",
            },
        ),
        migrations.CreateModel(
            name="Cookie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=99)),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
                (
                    "pdf",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=home.models.policy_media_path,
                        verbose_name="PDF",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
            ],
            options={
                "verbose_name_plural": "Cookie policy",
            },
        ),
        migrations.CreateModel(
            name="Donate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                (
                    "btc_desc",
                    tinymce.models.HTMLField(
                        blank=True, null=True, verbose_name="BTC Text"
                    ),
                ),
                ("btc", models.CharField(blank=True, max_length=42, null=True)),
                (
                    "eth_desc",
                    tinymce.models.HTMLField(
                        blank=True, null=True, verbose_name="ETH Text"
                    ),
                ),
                ("eth", models.CharField(blank=True, max_length=42, null=True)),
            ],
            options={
                "verbose_name_plural": "Donate page",
            },
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("media", models.FileField(blank=True, null=True, upload_to="home/")),
                ("text", tinymce.models.HTMLField(blank=True, null=True)),
                ("quote", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name_plural": "Homepage",
            },
        ),
        migrations.CreateModel(
            name="Privacy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=99)),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
                (
                    "pdf",
                    models.FileField(
                        blank=True,
                        max_length=255,
                        null=True,
                        upload_to=home.models.policy_media_path,
                        verbose_name="PDF",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
            ],
            options={
                "verbose_name_plural": "Privacy policy",
            },
        ),
        migrations.CreateModel(
            name="Terms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
                (
                    "pdf",
                    models.FileField(
                        blank=True,
                        max_length=255,
                        null=True,
                        upload_to=home.models.policy_media_path,
                        verbose_name="PDF",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
            ],
            options={
                "verbose_name_plural": "Terms of use",
            },
        ),
        migrations.CreateModel(
            name="Trademark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=99)),
                (
                    "text",
                    tinymce.models.HTMLField(
                        help_text="Legal Design. Clear. Concise. No legalese", null=True
                    ),
                ),
                (
                    "pdf",
                    models.FileField(
                        blank=True,
                        max_length=255,
                        null=True,
                        upload_to=home.models.policy_media_path,
                        verbose_name="PDF",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
            ],
            options={
                "verbose_name_plural": "Trademark",
            },
        ),
        migrations.CreateModel(
            name="TSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Skip if section 1",
                        max_length=99,
                        null=True,
                    ),
                ),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
                (
                    "text",
                    tinymce.models.HTMLField(
                        help_text="Legal Design. Clear. Concise. No legalese", null=True
                    ),
                ),
                (
                    "img",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=home.models.policy_media_path,
                        verbose_name="Image",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.terms",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Skip if section 1",
                        max_length=99,
                        null=True,
                    ),
                ),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
                (
                    "text",
                    tinymce.models.HTMLField(
                        help_text="Legal Design. Clear. Concise. No legalese", null=True
                    ),
                ),
                (
                    "img",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=home.models.policy_media_path,
                        verbose_name="Image",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.privacy",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Skip if section 1",
                        max_length=99,
                        null=True,
                    ),
                ),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
                (
                    "text",
                    tinymce.models.HTMLField(
                        help_text="Legal Design. Clear. Concise. No legalese", null=True
                    ),
                ),
                (
                    "img",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=home.models.policy_media_path,
                        verbose_name="Image",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.cookie",
                    ),
                ),
            ],
        ),
    ]
