# Generated by Django 3.2 on 2021-04-12 11:57

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('C', 'Collaboration'), ('J', 'Employment'), ('F', 'Feedback'), ('M', 'Misc')], default='C', max_length=255)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('textarea', tinymce.models.HTMLField(blank=True, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=19, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='Cookie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=99)),
                ('text', tinymce.models.HTMLField(null=True, verbose_name='Clear, concise')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='cookie/', verbose_name='PDF')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name_plural': 'Cookie policy',
            },
        ),
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('btc_desc', tinymce.models.HTMLField(blank=True, null=True, verbose_name='BTC Description')),
                ('btc', models.CharField(blank=True, max_length=250, null=True)),
                ('eth_desc', tinymce.models.HTMLField(blank=True, null=True, verbose_name='ETH Description')),
                ('eth', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name_plural': 'Donate page',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('background', models.FileField(blank=True, null=True, upload_to='homepage/')),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('quote', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Homepage',
            },
        ),
        migrations.CreateModel(
            name='Privacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=99)),
                ('text', tinymce.models.HTMLField(null=True, verbose_name='Clear, concise')),
                ('pdf', models.FileField(blank=True, max_length=255, null=True, upload_to='privacy/', verbose_name='PDF')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name_plural': 'Privacy policy',
            },
        ),
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('text', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Terms')),
                ('pdf', models.FileField(blank=True, max_length=255, null=True, upload_to='terms/', verbose_name='PDF')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name_plural': 'Terms of use',
            },
        ),
        migrations.CreateModel(
            name='Trademark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=99)),
                ('text', tinymce.models.HTMLField(null=True, verbose_name='Clear, concise, compelling')),
                ('pdf', models.FileField(blank=True, max_length=255, null=True, upload_to='Trademark/', verbose_name='PDF')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name_plural': 'Trademark',
            },
        ),
    ]
