# Generated by Django 3.2 on 2021-04-26 15:32

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookie',
            name='text',
            field=tinymce.models.HTMLField(help_text='Clear, concise, no legalese', null=True),
        ),
        migrations.AlterField(
            model_name='privacy',
            name='text',
            field=tinymce.models.HTMLField(help_text='Clear, concise, no legalese', null=True),
        ),
        migrations.AlterField(
            model_name='terms',
            name='text',
            field=tinymce.models.HTMLField(help_text='Clear, concise, no legalese', null=True, verbose_name='Terms'),
        ),
        migrations.AlterField(
            model_name='trademark',
            name='text',
            field=tinymce.models.HTMLField(help_text='Clear, concise, no legalese', null=True),
        ),
    ]
