# Generated by Django 3.2.2 on 2021-05-09 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='textarea',
            new_name='text',
        ),
    ]
