# Generated by Django 3.2.3 on 2021-05-16 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_textarea_contact_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
