# Generated by Django 3.2.4 on 2021-06-23 11:37

from django.db import migrations, models
import home.models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210622_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trademark',
            old_name='updated_at',
            new_name='updated',
        ),
        migrations.AddField(
            model_name='cookie',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='terms',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cookie',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=home.models.policy_media_path, verbose_name='PDF'),
        ),
        migrations.AlterField(
            model_name='donate',
            name='btc_desc',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='BTC Text'),
        ),
        migrations.AlterField(
            model_name='donate',
            name='eth_desc',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='ETH Text'),
        ),
        migrations.AlterField(
            model_name='page',
            name='background',
            field=models.FileField(blank=True, null=True, upload_to='home/'),
        ),
        migrations.AlterField(
            model_name='terms',
            name='pdf',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=home.models.policy_media_path, verbose_name='PDF'),
        ),
        migrations.AlterField(
            model_name='trademark',
            name='pdf',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=home.models.policy_media_path, verbose_name='PDF'),
        ),
    ]
