# Generated by Django 3.2.4 on 2021-06-23 12:06

from django.db import migrations, models
import django.db.models.deletion
import home.models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210623_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Skip if section 1', max_length=99, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('text', tinymce.models.HTMLField(help_text='Legal Design', null=True)),
                ('img', models.FileField(blank=True, null=True, upload_to=home.models.policy_media_path, verbose_name='Image')),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.cookie')),
            ],
        ),
        migrations.CreateModel(
            name='PSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Skip if section 1', max_length=99, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('text', tinymce.models.HTMLField(help_text='Legal Design, clear, concise, no legalese', null=True)),
                ('img', models.FileField(blank=True, null=True, upload_to=home.models.policy_media_path, verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='TSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Skip if section 1', max_length=99, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('text', tinymce.models.HTMLField(help_text='Legal Design', null=True)),
                ('img', models.FileField(blank=True, null=True, upload_to=home.models.policy_media_path, verbose_name='Image')),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.terms')),
            ],
        ),
        migrations.RemoveField(
            model_name='privacy',
            name='text',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.AddField(
            model_name='psection',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.privacy'),
        ),
    ]
