# Generated by Django 3.2.8 on 2021-10-06 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_background_page_media'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='created_at',
            new_name='created',
        ),
    ]
