# Generated by Django 3.2.8 on 2021-10-08 16:12

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_created_at_contact_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cookie',
            name='text',
        ),
        migrations.RemoveField(
            model_name='terms',
            name='text',
        ),
        migrations.AlterField(
            model_name='csection',
            name='text',
            field=tinymce.models.HTMLField(help_text='Legal Design. Clear. Concise. No legalese', null=True),
        ),
        migrations.AlterField(
            model_name='donate',
            name='btc',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
        migrations.AlterField(
            model_name='donate',
            name='eth',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
        migrations.AlterField(
            model_name='psection',
            name='text',
            field=tinymce.models.HTMLField(help_text='Legal Design. Clear. Concise. No legalese', null=True),
        ),
        migrations.AlterField(
            model_name='trademark',
            name='text',
            field=tinymce.models.HTMLField(help_text='Legal Design. Clear. Concise. No legalese', null=True),
        ),
        migrations.AlterField(
            model_name='tsection',
            name='text',
            field=tinymce.models.HTMLField(help_text='Legal Design. Clear. Concise. No legalese', null=True),
        ),
    ]
