# Generated by Django 3.2.6 on 2021-08-17 19:36

import django.core.files.storage
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import pathlib
import shop.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0003_alter_tag_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(default=1, null=True, unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('name_product', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to=shop.models.shop_media_path, verbose_name='Image')),
                ('price', models.DecimalField(decimal_places=2, default=9.99, max_digits=9, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price (€)')),
                ('product_type', models.CharField(choices=[('E', 'Ebook'), ('A', 'Audio'), ('P', 'Physical')], default='E', max_length=8)),
                ('text', tinymce.models.HTMLField(blank=True, help_text='Benefits per costs', null=True, verbose_name='Description')),
                ('is_digital', models.BooleanField(default=False, help_text='Digital (in stock, no shipment)')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('in_stock', models.BooleanField(default=False, verbose_name='In Stock')),
                ('active', models.BooleanField(default=True, help_text='Hide if unavailable', verbose_name='Show')),
                ('recommend', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='shop/', verbose_name='PDF Brochure/Manual')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category')),
                ('tags', models.ManyToManyField(to='tags.Tag')),
            ],
            options={
                'verbose_name_plural': 'Products',
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='ProductFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/home/mgb/c/cw/media/protected')), upload_to=shop.models.upload_product_file_loc)),
                ('free', models.BooleanField(default=False)),
                ('user_required', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
    ]
