# Generated by Django 4.1.2 on 2022-10-05 19:29

import django.core.files.storage
from django.db import migrations, models
import pathlib
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productfile",
            name="file",
            field=models.FileField(
                storage=django.core.files.storage.FileSystemStorage(
                    location=pathlib.PurePosixPath("/home/mgb/ce/media/protected")
                ),
                upload_to=shop.models.upload_product_file_loc,
            ),
        ),
    ]
