# Generated by Django 3.2.6 on 2021-08-24 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20210824_1338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name_product',
            new_name='name',
        ),
    ]
