# Generated by Django 3.2.6 on 2021-08-24 15:52

from django.db import migrations, models
import django.db.models.deletion
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_product_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=False, help_text='Hide if unavailable', verbose_name='Show'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(null=True, upload_to=shop.models.shop_media_path, verbose_name='Image/GIF'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_digital',
            field=models.BooleanField(default=True, help_text='No shipment', verbose_name='Digital'),
        ),
    ]
