# Generated by Django 3.2.6 on 2021-08-24 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_product_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='qty_instock',
        ),
    ]
