# Generated by Django 3.2.6 on 2021-08-26 16:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_product_qty_instock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='recommend',
        ),
        migrations.AddField(
            model_name='product',
            name='order_qty',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
