# Generated by Django 3.2.6 on 2021-08-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20210826_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='order_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19),
        ),
    ]
