# Generated by Django 3.2.6 on 2021-08-26 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_product_order_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='order_total',
        ),
    ]
