# Generated by Django 3.2.6 on 2021-08-28 17:41

from django.db import migrations
import shop.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_remove_product_order_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=sorl.thumbnail.fields.ImageField(null=True, upload_to=shop.models.shop_media_path, verbose_name='Image/GIF'),
        ),
    ]
