# Generated by Django 3.2.6 on 2021-08-28 18:06

from django.db import migrations
import shop.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_alter_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=sorl.thumbnail.fields.ImageField(null=True, upload_to=shop.models.shop_media_path, verbose_name='Image/GIF'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=shop.models.shop_media_path),
        ),
    ]
