# Generated by Django 3.2.8 on 2021-10-06 13:42

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_auto_20210828_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='user',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='updated_at',
            new_name='updated',
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(null=True, upload_to=shop.models.shop_media_path, verbose_name='Image/GIF'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=shop.models.shop_media_path),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
        migrations.DeleteModel(
            name='ProductReview',
        ),
    ]
