# Generated by Django 3.1.7 on 2021-03-17 23:01

import apps.products.models
import django.core.files.storage
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(default=1, null=True, unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('name_product', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('description', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Benefits')),
                ('price', models.DecimalField(decimal_places=2, default=99.99, max_digits=9, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price (EUR)')),
                ('img', models.ImageField(blank=True, null=True, upload_to=apps.products.models.product_img_path, verbose_name='Image')),
                ('available', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_digital', models.BooleanField(default=False, verbose_name='Digital (no shipment, no quantity)')),
                ('quantity', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('product_type', models.CharField(choices=[('E', 'Ebook'), ('A', 'Audio'), ('P', 'Physical')], default='E', max_length=8)),
                ('recommended', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Products',
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='ProductFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/home/mgb/c/c1/static_cdn/protected_root'), upload_to=apps.products.models.upload_product_file_loc)),
                ('free', models.BooleanField(default=False)),
                ('user_required', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
