# Generated by Django 3.1.7 on 2021-03-19 18:35

import apps.products.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfile',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/mnt/c/Users/39345/static_cdn/protected_root'), upload_to=apps.products.models.upload_product_file_loc),
        ),
    ]
