# Generated by Django 3.1.7 on 2021-03-20 12:59

import apps.products.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210319_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfile',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/home/mgb/c/static_cdn/protected_root'), upload_to=apps.products.models.upload_product_file_loc),
        ),
    ]
