# Generated by Django 3.1.7 on 2021-03-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20210327_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('E', 'Ebook'), ('A', 'Audio'), ('P', 'Physical')], default='E', max_length=8),
        ),
    ]
