# Generated by Django 3.1.7 on 2021-03-30 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(default=False, verbose_name='In Stock'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_digital',
            field=models.BooleanField(default=False, verbose_name='Digital (in stock, no shipment)'),
        ),
    ]
