# Generated by Django 3.2.8 on 2021-10-06 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created', '-updated'], 'verbose_name_plural': 'Orders'},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='updated_at',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='productpurchase',
            old_name='updated_at',
            new_name='updated',
        ),
    ]
