# Generated by Django 3.2 on 2021-04-12 11:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import essays.models
import meta.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0002_alter_tag_id'),
        ('team', '0002_alter_member_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=90, null=True)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('bio', tinymce.models.HTMLField(null=True, verbose_name='Bio')),
                ('img', models.FileField(blank=True, null=True, upload_to=essays.models.author_image_path, verbose_name='Pic')),
                ('author_url', models.URLField(blank=True, null=True, verbose_name="Author's website")),
            ],
            options={
                'verbose_name_plural': 'Independent authors',
            },
        ),
        migrations.CreateModel(
            name='Essay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(default=1, null=True, unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('image', models.FileField(blank=True, null=True, upload_to=essays.models.essay_media_path, verbose_name='Header image')),
                ('title', models.CharField(db_index=True, max_length=99, null=True)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('audio', models.FileField(blank=True, null=True, upload_to=essays.models.essay_media_path, verbose_name='Record reading')),
                ('text', tinymce.models.HTMLField(null=True, verbose_name='Exordium (Pathos)-> Narratio -> Confirmatio (Logos) -> Refutatio (Ethos) -> Peroration (Pathos)[View->srcode->class="fl"]')),
                ('abstract', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Abstract')),
                ('img', models.FileField(blank=True, null=True, upload_to=essays.models.essay_media_path, verbose_name='Image')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('publish', models.BooleanField(default=False)),
                ('recommend', models.BooleanField(default=False)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='essays.author')),
                ('author_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='C_team', to='team.member')),
                ('tags', models.ManyToManyField(to='tags.Tag')),
            ],
            options={
                'verbose_name_plural': 'Essays',
                'ordering': ['index'],
            },
            bases=(meta.models.ModelMeta, models.Model),
        ),
    ]
