# Generated by Django 3.2 on 2021-04-26 15:32

from django.db import migrations, models
import essays.models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_url',
            field=models.URLField(blank=True, help_text='Website of the author', null=True),
        ),
        migrations.AlterField(
            model_name='essay',
            name='audio',
            field=models.FileField(blank=True, help_text='Record reading', null=True, upload_to=essays.models.essay_media_path),
        ),
        migrations.AlterField(
            model_name='essay',
            name='publish',
            field=models.BooleanField(default=False, help_text='Ensure to edit before publishing'),
        ),
        migrations.AlterField(
            model_name='essay',
            name='text',
            field=tinymce.models.HTMLField(help_text='Exordium (Pathos)-> Narratio -> Confirmatio (Logos) -> Refutatio (Ethos) -> Peroration (Pathos)[View->srcode->class="fl"]', null=True),
        ),
    ]
