# Generated by Django 3.2.3 on 2021-05-23 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0003_auto_20210519_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='author',
            field=models.ForeignKey(blank=True, help_text='Independent author', null=True, on_delete=django.db.models.deletion.CASCADE, to='essays.author'),
        ),
    ]
