# Generated by Django 3.2.4 on 2021-06-09 20:33

from django.db import migrations, models
import django.db.models.deletion
import essays.models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0004_alter_essay_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='essay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='essays.essay'),
        ),
        migrations.AddField(
            model_name='section',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to=essays.models.essay_media_path),
        ),
        migrations.AddField(
            model_name='section',
            name='text',
            field=tinymce.models.HTMLField(help_text='Exordium (Pathos)-> Narratio -> Confirmatio (Logos) -> Refutatio (Ethos) -> Peroration (Pathos)[View->srcode->class="fl"]', null=True),
        ),
    ]
