# Generated by Django 3.2.4 on 2021-06-09 20:57

from django.db import migrations, models
import essays.models


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0005_auto_20210609_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to=essays.models.essay_media_path, verbose_name='Image'),
        ),
    ]
