# Generated by Django 3.2.4 on 2021-06-09 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0006_auto_20210609_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='essay',
            name='img',
        ),
        migrations.RemoveField(
            model_name='essay',
            name='text',
        ),
        migrations.AlterField(
            model_name='essay',
            name='publish',
            field=models.BooleanField(default=False, help_text='Edit before publishing'),
        ),
    ]
