# Generated by Django 3.2.4 on 2021-06-09 22:35

from django.db import migrations, models
import django.db.models.deletion
import essays.models


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0007_auto_20210609_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='author',
            field=models.ForeignKey(blank=True, help_text='Add if independent author', null=True, on_delete=django.db.models.deletion.CASCADE, to='essays.author'),
        ),
        migrations.AlterField(
            model_name='essay',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=essays.models.essay_media_path, verbose_name='Cover image'),
        ),
        migrations.AlterField(
            model_name='essay',
            name='recommend',
            field=models.BooleanField(default=False, help_text='Must-read'),
        ),
        migrations.AlterField(
            model_name='section',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(blank=True, help_text='Skip if section 1', max_length=90, null=True),
        ),
    ]
