# Generated by Django 3.2.4 on 2021-06-09 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0008_auto_20210609_2235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='essay',
            old_name='image',
            new_name='img',
        ),
    ]
