# Generated by Django 3.2 on 2021-04-17 15:31

import django.core.files.storage
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfile',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/static_cdn/protected_root'), upload_to=products.models.upload_product_file_loc),
        ),
    ]
