# Generated by Django 3.2.4 on 2021-06-21 19:57

import django.core.validators
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=tinymce.models.HTMLField(blank=True, help_text='Benefits per costs', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=9.99, max_digits=9, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price (€)'),
        ),
    ]
