# Generated by Django 3.2.4 on 2021-06-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210621_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='products/', verbose_name='PDF Brochure/Manual'),
        ),
    ]
