# Generated by Django 3.2.4 on 2021-06-23 14:31

import django.core.files.storage
from django.db import migrations, models
import pathlib
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfile',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/home/mgb/c/static_cdn/media/protected')), upload_to=products.models.upload_product_file_loc),
        ),
    ]
