# Generated by Django 3.2.4 on 2021-06-23 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_productfile_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='text',
        ),
    ]
